### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by simonpeter** [cnbbooks/lfe-rebar3-quick-start#15]
When issuing the command

rebar3 new lfe-lib my-test-lib

I get

template not found.

I'm working through the "LFE Quick Start with rebar3_lfe" and am on the "Creating a New Project" page.
My OS is Ubuntu Linux 20.04 and my version of Erlang is:

Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Thank you.

**Comment by oubiwann** [comment]
Could you paste your `rebar.config` in a comment?

**Comment by oubiwann** [comment]
Hrm, looks like there isn't a step for updating the global `rebar.config` (see https://www.rebar3.org/docs/using-available-plugins).

This was added in another LFE book ... ah, found it:
* https://lfe.io/reference/lfe-rebar3/current/setup/plugin.html

But that assumes general knowledge of how rebar3 works, too. I need to update both books to:
* [x] explicitly show the default global `rebar.config` path, and
* [x] link to the official `rebar3` docs

Lastly, I need to:

* [x] update the quick start to show the same code example of what the global `rebar.config` file should look like after adding the plugin dependency.

**Comment by oubiwann** [comment]
Until I update the docs with better explicit initial steps, you can continue with the "Quick Start" if you do this:
```
mkdir -p ~/.config/rebar3/
touch ~/.config/rebar3/rebar.config
```

And then open up that file, adding the following:
```erlang
{plugins, [
  {rebar3_lfe,
    {git, "https://github.com/lfe-rebar3/rebar3_lfe.git", {tag, "0.2.0"}}}
]}.
```

**Comment by simonpeter** [comment]
Wow, thank you for helpful and speedy responses. I will be able to continue in the tutorial later this afternoon and I will use your provided work around and report back afterwards.

**Comment by simonpeter** [comment]
I applied your workaround and have made it to the next page "Hitting the Code". (I wondered whether the problem was with the snap version of Erlang, so I uninstalled it and reinstalled via apt-get, but did not seem to make any difference.)

After entering the "rebar3 new repl" command I got another "template not found" error.

Pasting the output below:

simon@Bert:~/Projects/Learn/LFE/my-test-lib$ rebar3 new repl
===> Fetching rebar3_lfe (from {git,"http://github.com/lfe-rebar3/rebar3_lfe",
                      {branch,"master"}})
===> Fetching lfe (from {git,"http://github.com/rvirding/lfe",{branch,"develop"}})
===> Compiling lfe
_build/default/plugins/lfe/src/lfe_io_pretty.erl:23: Warning: export_all flag enabled - all functions will be exported

_build/default/plugins/lfe/src/lfe_shell.erl:404: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/plugins/lfe/src/lfe_init.erl:81: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/plugins/lfe/src/lfe_macro_include.erl:306: Warning: variable 'Line' is unused

_build/default/plugins/lfe/src/lfe_lint.erl:1501: Warning: function add_errors/3 is unused

_build/default/plugins/lfe/src/lfe_eval.erl:736: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/plugins/lfe/src/lfe_eval.erl:793: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/plugins/lfe/src/lfe_types.erl:37: Warning: export_all flag enabled - all functions will be exported

_build/default/plugins/lfe/src/lfe_comp.erl:96: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/plugins/lfe/src/lfescript.erl:62: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/plugins/lfe/src/lfescript.erl:188: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/plugins/lfe/src/lfe_macro.erl:606: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/plugins/lfe/src/lfe_macro.erl:626: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

_build/default/plugins/lfe/src/lfe_codegen.erl:33: Warning: export_all flag enabled - all functions will be exported

===> Compiling rebar3_lfe
template not found.
simon@Bert:~/Projects/Learn/LFE/my-test-lib$

**Comment by oubiwann** [comment]
Hrm. I just tried this on a completely clean Docker image, with no problems. Here's a transcript of the entire session:

```
$ docker run -it --entrypoint=bash erlang:23.0
```
```
root@5b7378eef859:/# mkdir -p ~/.config/rebar3
root@5b7378eef859:/# echo '{plugins, [
>   {rebar3_lfe,
>     {git, "https://github.com/lfe-rebar3/rebar3_lfe.git", {tag, "0.2.0"}}}
> ]}.
> ' > ~/.config/rebar3/rebar.config
root@5b7378eef859:/# rebar3 new lfe-lib
===> Writing my-lfe-lib/README.md                                                                                                                                                           
===> Writing my-lfe-lib/LICENSE                                                                                                                                                             
===> Writing my-lfe-lib/rebar.config                                                                                                                                                        
===> Writing my-lfe-lib/.gitignore                                                                                                                                                          
===> Writing my-lfe-lib/src/my-lfe-lib.lfe                                                                                                                                                  
===> Writing my-lfe-lib/src/my-lfe-lib.app.src                                                                                                                                              
root@5b7378eef859:/# cd my-lfe-lib/                                                                                                                                                         
root@5b7378eef859:/my-lfe-lib# rebar3 lfe repl
```
```
...
lfe>
```

**Comment by oubiwann** [comment]
oh, hehe -- you've got a typo 😄 

You want to type the following instead:

```
$ rebar3 lfe repl
```

(You typed `rebar3 new repl` so rebar3 is trying to find the template for creating a new repl ...)

**Comment by simonpeter** [comment]
I appreciate all of your help and I hate to be "that person", but I copied the "rebar3 new repl" command straight from the "REPL Me Up!" section on the "Hitting the Code" page.

I have previously written a number of onboarding guides for corporate projects that I've worked on, and I completely appreciate how tough it is to write getting started or tutorial guides for technologies.

**Comment by oubiwann** [comment]
Oh, hey -- didn't see this until just now! Thanks so much, @simonpeter! That means you've found another bug that needs to be fixed in the docs!! I'll track it here, and close the ticket when I fix that.

Thanks again!

**Comment by oubiwann** [comment]
P.S. Thanks for your wonderful attitude and your saintly patience!

**Comment by simonpeter** [comment]
Glad to help.
And it's my job to be patient, I'm a pastor. :-)

**Comment by oubiwann** [comment]
Okay, addressed all the issues here from this ticket.

Also, since the code section was too long and didn't match the rest of the bite-sized chunks, I split that up, too :-) 

Will publish shortly ...

**Comment by oubiwann** [comment]
Done!

Thanks again with your QA help!!!
