### ISSUE TITLE
errors when 'Creating a New Project' tutorial

### ISSUE THREAD

**Issue by ferriswheel** [cnbbooks/lfe-rebar3-quick-start#26]
$ rebar3 new lfe-lib my-test-lib
===> Fetching rebar3_lfe (from {git,"https://github.com/lfe-rebar3/rebar3_lfe.git",
                      {branch,"master"}})
===> Fetching lfe v2.0.0
===> Fetching ltest v0.13.0
===> Fetching rebar_cmd v0.2.6
===> Fetching rebar3_hex v7.0.1
===> Fetching hex_core v0.8.4
===> Fetching verl v1.1.1
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
.cache/rebar3/plugins/rebar3_hex/src/rebar3_hex_organization.erl:391:5: Warning: public_key:ssh_encode/2 is deprecated and will be removed in OTP 26; use ssh_file:encode/2 instead

===> Analyzing applications...
===> Compiling rebar_cmd
===> "/home/john/.cache/rebar3/plugins/rebar_cmd/ebin/rebar_cmd.app" is missing applications entry
===> Fetching erlang_color v1.0.0
===> Analyzing applications...
===> Compiling lfe
.cache/rebar3/plugins/lfe/src/lfe_types.erl:76:21: Warning: variable '_L' is bound multiple times in this pattern. If you mean to ignore this value, use '_' or a different underscore-prefixed name
.cache/rebar3/plugins/lfe/src/lfe_types.erl:76:38: Warning: variable '_L' is bound multiple times in this pattern. If you mean to ignore this value, use '_' or a different underscore-prefixed name

===> Compiling ltest
===> Compiling rebar3_lfe
===> Compiling color
===> The 'name' variable is often associated with Erlang module names and/or file names. The value submitted (my-test-lib) isn't an unquoted Erlang atom. Templates generated may contain errors.
===> Writing my-test-lib/README.md
===> Writing my-test-lib/LICENSE
===> Writing my-test-lib/rebar.config
===> Writing my-test-lib/.gitignore
===> Writing my-test-lib/src/my-test-lib.lfe
===> Writing my-test-lib/src/my-test-lib.app.src
===> Writing my-test-lib/test/my-test-lib-tests.lfe

OS:       linux
distro:  gentoo
erlang: 24.0.2
rebar:   3.17.0

regards

john

**Comment by simonelnahas** [comment]
Similar error here:
```bash
$ rebar3 new lfe-lib my-test-lib
template not found.

```

**Comment by oubiwann** [comment]
More recent versions of rebar3 + lfe_rebar3 address this (ideally, use the latest release).
