### ISSUE TITLE
Tutorial Example Fails

### ISSUE THREAD

**Issue by g3ntleman** [cnbbooks/lfe-rebar3-quick-start#3]
I tried to run the example from page 2.md of the tutorial after installing lfetool as described on the latest macOS. I had the problem of rebar being rebar3 nowadays. I symlinked rebar to rebar3 to get the installation to finish.

I suspect, the error below is a followup-error from above workaround: lutil does not seem to build with rebar3.

Should I use the seemingly deprecated rebar(2) or is there a better fix?

```
 > lfetool new library lfe-test-lib   
Setting up starter library project lfe-test-lib ...
Leeres Git-Repository in /Users/theisen/Projects/Work/lfe-test-lib/.git/ initialisiert
Removing EUnit test files ...
rm: ./.eunit/*.beam: No such file or directory
make: [clean-eunit] Error 1 (ignored)
Getting dependencies ...
===> Verifying dependencies...
===> Fetching lfe (from {git,"git://github.com/rvirding/lfe.git",{tag,"v0.9.0"}})
===> Fetching ltest (from {git,"git://github.com/lfex/ltest.git",{tag,"0.4.1"}})
===> Fetching lutil (from {git,"https://github.com/lfex/lutil.git",{tag,"0.5.1"}})
===> Dependency failure: source for lutil does not contain a recognizable project and can not be built
```

**Comment by oubiwann** [comment]
Yeah, we are going to re-work this doc to use the new rebar3_lfe plugin, and not the very ancient lfetool :-(

**Comment by oubiwann** [comment]
New `rebar3_lfe`-based quick start is up: http://lfe.io/rebar3-quick-start/index.html
