### ISSUE TITLE
Mention how to run tests in the Tutorial

### ISSUE THREAD

**Issue by g3ntleman** [cnbbooks/lfe-rebar3-quick-start#4]
The tutorial at lfetool-quick-start/2.md fails to mention how to run unit tests - just shows the output.

**Comment by oubiwann** [comment]
The tests have been removed from the current version, since that's under active development in `rebar3_lfe`. Once that has landed, we'll be updating the quick start to show how to run them (hint: the non-LFE community-standard`rebar3 eunit1` works for LFE too! But there will be more ...)
